language: "es"

pipeline:
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "LexicalSyntacticFeaturizer"
  - name: "DIETClassifier"
    epochs: 100
  - name: "EntitySynonymMapper"
  - name: "ResponseSelector"
    epochs: 50

policies:
  - name: "MemoizationPolicy"
    max_history: 5
  - name: "RulePolicy"
    core_fallback_action_name: "action_default_fallback"
    core_fallback_threshold: 0.1  # Reduce este valor si es necesari
  - name: "TEDPolicy"
    max_history: 5
    epochs: 100
    constrain_similarities: true

assistant_id: "20241018-162024-andante-chili"